import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.scss'

import Circle from '../assets/main_circle.svg'
import SideCircle from '../assets/side_circle.svg'
import BottomCircle from '../assets/bottom_circle.svg'

// reactstrap components
import { Row, Col } from 'reactstrap'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Don't Overreact</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/eye.ico" />
      </Head>

      <div className={styles.topBar}>
        <div className={styles.topBarContent}>
          <p className={styles.item}>
            <a href="/api/hello">Item 1</a>
          </p>
          <p className={styles.item}>
            <a href="/api/hello">Item 2</a>
          </p>
          <p className={styles.home}>
            <a href="/">Home</a>
          </p>
          <p className={styles.item}>
            <a href="/api/hello">Item 3</a>
          </p>
          <p className={styles.item}>
            <a href="/api/hello">Item 4</a>
          </p>
        </div>
      </div>

      <main className={styles.main}>
        <div className={styles.container}>
          <Row>
            <Col xl="7" className="d-none d-lg-block">
              <div className={styles.svgContainer}>
                <SideCircle className={styles.sideLeftSvgContent} />
                <Circle className={styles.mainSvgContent} />
              </div>
            </Col>
            <Col xl="4" md="12" className="p-5">
              <h1 className={styles.title}>My mother told me</h1>
              <p className={styles.info}>
                The song My mother told me, also known as Þat mælti mín móðir in
                its ninth-century old Norse form, is probably most recognizable
                through the popular show Vikings. However, as an archaeologist,
                this song ignites something inside of this author’s never-ending
                thought experiments on this population which existed during the
                Iron Age.
              </p>
              <p className={styles.info}>
                The Vikings were likely faced with several economic, political,
                and social pressures in Norway during the Viking Age, and
                started to venture abroad for various reasons.
              </p>
            </Col>
          </Row>
        </div>
      </main>
      <div className={styles.bottomContainer}>
        <div className="d-none d-lg-block">
          <BottomCircle className={styles.sideBottomSvgContent} />
        </div>
      </div>
    </div>
  )
}

export default Home
